const messageConstant = {
    SUCCESS: 'Success',
    ERROR: 'Error',
    LOGIN_FAILED: 'Username or Password is invalid',
    ACCESS_DENIED: 'You have no permission..!',
    ERROR_VERIFY_PERMISSION: 'An error occurred while verifying permissions.',
    INTERNAL_SERVER_ERROR: 'Internal server error',
    UNIQUE_CONSTRAINT: 'Email or phone number already exists.',
    EMAIL_NAME_EXISTS: 'Email or business name already exists.',
    USER_NOT_EXIST: 'User not exist on this email',
    USER_EXIST: 'User already exist. Please login!',
    USER_CREATED: 'User created successfully',
    USER_CREATION_FAILED: 'User creation failed',
    BOOK_CREATION_FAILED: 'Book creation failed',
    BOOK_CREATED: 'Book created successfully',
    BOOK_RETRIEVED: 'Book retrieved successfully',
    BOOK_UPDATED: 'Book updated successfully',
    BOOK_DELETED: 'Book deleted successfully',
    BOOK_NOT_FOUND: 'Book not found',
    BOOK_ALREADY_EXISTS:
        'Book with same name already exist. Please choose a different name!',
    BOOK_NAME_UNIQUE:
        'The book name must be unique. Please choose a different name.',
    BAD_REQUEST: 'Bad request',
    VALIDATION_FAILED: 'Validation failed',
    EMAIL_IN_USED: 'Email already in use',
    FILE_NOT_UPLOADED:
        'Please Upload the file with valid extension(.png, .jpg, .jpeg)',
    WRONG_PASSWORD: 'Wrong password',
    NOT_AUTHORIZED: 'Not authorized',

    RESET_EMAIL_SENT: 'Reset email sent successfully',
    RESET_EMAIL_FAILED: 'Reset email failed',
    PASSWORD_RESET: 'Password reset successfully',
    INVALID_RESET_TOKEN: 'Invalid or expired Token',
    EMAIL_NOT_MATCH: 'Email and Confirm Email are not the same',
    PASSWORD_NOT_MATCH: 'Password and Confirm Password are not the same',
    NOT_GET_HASHED_TOKEN: 'Hashed token cannot get, please try again',
    FILE_NOT_FOUND: 'File not found',
    ERROR_DOWNLOAD_FILE: 'Error when downloading file',
    CATEGORY_EXISTS: 'Category already exists.',
    CATEGORY_CREATED: 'Category created successfully.',
    CATEGORY_NOT_EXISTS: 'Category not exists.',
    CATEGORY_UPDATED: 'Category updated successfully.',
    CATEGORY_NAME_UNIQUE:
        'The Category name must be unique. Please choose a different name.',
    CATEGORY_HAS_BOOKS: 'Category has books.',
    CATEGORY_DELETED: 'Category deleted successfully',
    CATEGORY_RETRIEVED: 'Category retrieved successfully',
};

export default messageConstant;
